### ISSUE TITLE
Gap between tiles of different colours in offset tilesheet

### ISSUE THREAD

**Issue by Galatolol** [kelsin/18xx#115]
Is it possible to not have this empty line between tiles of different colours in offset mode?

![kelsin](https://user-images.githubusercontent.com/10097748/68812837-4b72a900-0674-11ea-8dd5-37e97c84e9b2.png)

**Comment by th3tick** [comment]
I believe it's done to maximize the bleed to allow for inaccuracies in cuts, so I don't think that's particularly desirable.

**Comment by kelsin** [comment]
Yeah, the reason for the row is that one small angle mishap and you might have the wrong colors bleed onto the edge of other tiles. On the die cutter layout I plan on laying out tiles vertically so that we only need ONE blank tile to prevent color bleed, but on this layout you really need the whole row. We can definitely add an option to NOT include the row of space for those that don't want it however.

I'll keep this issue open to do that:

- [ ] Add an option to remove blank rows from all tile layouts

If there is something else needed here let me know!

**Comment by kelsin** [comment]
Option added to remove tile gaps, no fixes for bleeds have been done. If you have issues let me know but will be hesitant to fix any bleed issues due to only this.
