### ISSUE TITLE
bleed not taking into account borders

### ISSUE THREAD

**Issue by th3tick** [kelsin/18xx#117]
When developing the tile set for Powerrails, I realized it's ignoring the border setting and only organizing bleeds for the tracks lining up.  When there are borders, the borders should override the tracks aligning, and try to group by matching border colors instead.

Of course, when those borders are dashed, all bets are off...

**Comment by kelsin** [comment]
Very good note, yeah the bleed stuff wasn't paying attention to borders at all which will change some stuff!

**Comment by th3tick** [comment]
More things this is true for:
- striped tiles where the stripes don't align
- tiles with cities over the edges
- tiles with more than one path at a given edge (e.g. Met tiles for 1825)

while some of these might be recognizable, it might be worthwhile to have a way to specify something like:

"isolate": true

for the screwier cases.

**Comment by kelsin** [comment]
Yep, added three options that affect tile sheet drawing:

* `"group": "name"`: This overrides how the tiles are grouped, It defaults to the color but you can put something here to have the tiles grouped separately. If you name the group `individual`, it has special meaning and will put the tile in a group by itself. Can see examples of this in the 18Mex tiles, 18Harz (for borders) and 1825 (for stripes).
* `"rotation": 60`: This overrides the rotation (that's normally based on the last tile's track. You can see an example of this on 18Mex for Mexico City to make sure the tiles align.
* `"mask": "hexMask"`: This overrides what mask to use for the tile, You can see an example on 18Mex, since Mexico City will be cut out by hand, I didn't want normal masks on the tiles.
