### ISSUE TITLE
striped tiles don't generate to a PDF properly

### ISSUE THREAD

**Issue by th3tick** [kelsin/18xx#125]
When I try to print tiles from the tool, in either the case of actually printing, or using it to generate the PDF, the number of stripes in striped tiles drops and otherwise goes wonky.  The first file shows the tiles on the screen, and the second shows what it gets when printed to a PDF.

<img width="805" alt="Screen Shot 2019-12-04 at 12 06 52 AM" src="https://user-images.githubusercontent.com/48138042/70120580-2b5a5800-162a-11ea-8ae8-493967b2817f.png">
<img width="808" alt="Screen Shot 2019-12-04 at 12 07 30 AM" src="https://user-images.githubusercontent.com/48138042/70120582-2b5a5800-162a-11ea-8c35-aec5218d7ecd.png">

**Comment by kelsin** [comment]
I removed gradiants and implemented stripped tiles for real. So now you can say a tile or map hex is `anycolor/anycolor` and it works. If the background (first) color is `yellow` or `green` it rotates the stripes, otherwise they are vertical. This makes the basic 1825 tiles work... but please let me know if you want it different. Right now the stripe width was set to duplicate 1825, can be set to configurable later if we want.
