### ISSUE TITLE
Market is rendering badly when printing

### ISSUE THREAD

**Issue by iamds** [kelsin/18xx#32]
I've noticed previously and am still seeing that when printing the market it is being rendered on portrait paper instead of landscape (maybe).

When running:
 yarn print 18Mex
the market ends up looking like the attached pdfs
[market.pdf](https://github.com/kelsin/18xx/files/3154169/market.pdf)
[market-paginated.pdf](https://github.com/kelsin/18xx/files/3154170/market-paginated.pdf)

**Comment by kelsin** [comment]
18Mex has not been fully checked for errors btw, just in case, any extra eyes to find problems would be great.

I have not gone through stock markets and corrected layout errors at all, so I definitely see (and can reproduce) that the market.pdf has overlap of the components. I will be looking at that soon in order to fix. However it does appear to be printing in landscape which is good.

The pagination one is definitely a bug and one that I just fixed and will be fixing in a better way in a future update related to #19. Currently it's computing the pagination in portrait and then printing on landscape paper which results in that bad layout. Committing a fix for this now, but it's not going to solve the layout problems which won't be solved until #22.
